# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#https://github.com/UncleStevie1/UncleStevie1-FAMILY1st/actions/runs/5416967678/job/15299534626#step:3:75
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:SOL: DMdkNDxB8Q3B5vMUE6GisoiqkUDpMWHiSrkRty7L37fM, SOL: E7FmNkSDYMCHQtY8LBJbqVoMqUScdaU2FDNc3fefPwCu, ETH: 0x531515654fd414f7acF12CF5cEa18D0D409Dbce4, ETH: 0x40757B5Ec5A6915862A3A572B313026e8a66294E, DOGE: xpub6C8kYN4rLqnwYBJ19DCS7WzEU7ZXffijh6TcbBPkK9TorcKZF7RWMWTYvpEbVfhBFxHCDm1RnXBwfHgXkUzM372dWBvkiX7zQL6qzyUdh3y, BTC: xpub6C2a4Qbvqd19QP1TBwdn7XrUKDvX8C1SkaB1Q2k1auyZirsuq6wYzPw42sbXp3KyBzbzFY7879FbpZU7pQq9GEztitTmucJyDMM9bB9aE3p, LTC: xpub6BnTkcnc6pvcTAj1uLSCmLnDjxWmkykQDpbuGpgTruhKpwp7ftuq2pPTbsmLjvLy3NbykAWxz8urtLAzHYa4BemJDYCaHpVUas5n3rLfoCS
    branches: [ "main" ]
    workflow_dispatch:0x838E959890090F350Da8e0716cB6983B96e1E147

env:https://github.com/enloestevie281/UncleStevie1-FAMILY1st/issues/2#top
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}https://github.com/UncleStevie1/UncleStevie1-FAMILY1st/blob/main/.github/workflows/azure-webapps-node.yml
